version: "3.8"
 
services:
# Makes a containorized postgres database on port 5432. Injects user, password, 
# and db name vars via enviornmental variables that are injected.
# Healthcheck to make sure app deploys correctly and is connected to db.
  db:
    image: postgres:15
    container_name: itemhealth-db
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: itemhealth
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d itemhealth"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
      
 # Makes container with the app on variable 8080. 
 # stores data in defined volume location.
 # as our server instance has max 2 gb ram, we set the deploy limit so
 # deployment doesn't fail.
  app:
    build: .
    container_name: itemhealth-app
 
    ports:
      - "8080:8080"
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          memory: 2G
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/itemhealth
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DOCKER_API_VERSION=1.43
      - MAVEN_OPTS=-Xmx1024m
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    
 # Contanerized mailhog instance to trap emails
 # uses the mailhog api to display trapped emails on frontend.
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    expose:
      - "8025"
      - "1025"
