
# Server
spring.application.name=itemhealth
server.forward-headers-strategy=framework

# Logging
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.directory=logs
# Host, Remote Logname, User, Time, Request Line, Status, Bytes
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b

#DB
spring.datasource.url=jdbc:postgresql://db:5432/itemhealth
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Mybatis
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=com.healthapp.itemhealth.model
mybatis.mapper-locations=classpath:mappers/*.xml

# Mailhog config
spring.mail.host=mailhog
spring.mail.port=1025
# since mail is captured and shown only, actual security isn't necessary
# but if were a real app it would need to be setup
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.username=${SPRING_MAIL_USERNAME:admin@example.com}
mailhog.api.url=${MAILHOG_URL:http://mailhog:8025}

# Optimization
spring.jmx.enabled=false

spring.security.user.name=unused