
-- Flywaydb migration files, below is the schema for employee.
-- After is the boss schema and subordinate table schema in file 2.
-- all items have the employee_id attribute as a foreign key.

CREATE TABLE employee (
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    title TEXT NOT NULL,
    boss TEXT,
    boss_role BOOLEAN NOT NULL,
    has_boss BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    username VARCHAR(50) UNIQUE,
    password VARCHAR(255),
    boss_id BIGINT,
    email TEXT NOT NULL DEFAULT 'fake@gmail.com'
   
);