CREATE TABLE boss (
    boss_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    name TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE boss_subordinates (
    boss_id BIGINT NOT NULL,
    subordinate_id BIGINT NOT NULL,
    PRIMARY KEY (boss_id, subordinate_id)
);
