CREATE TABLE laptop (
    laptop_id       BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    os_version      INT         NOT NULL DEFAULT 1,
    last_os_update TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    need_to_update  BOOLEAN     NOT NULL DEFAULT FALSE,
    laptop_year     INT         NOT NULL DEFAULT EXTRACT(YEAR FROM CURRENT_DATE),
    to_renew        BOOLEAN     NOT NULL DEFAULT FALSE,
    in_use          BOOLEAN     NOT NULL DEFAULT FALSE,
    employee_id     BIGINT,
    created_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT laptop_employee_id_fkey 
        FOREIGN KEY (employee_id) 
        REFERENCES employee(employee_id) 
        ON DELETE CASCADE
);