CREATE TABLE laptop (
    laptop_id       BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    os_version      INT,
    last_os_update TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    need_to_update  BOOLEAN     NOT NULL DEFAULT FALSE,
    laptop_year     INT         NOT NULL,
    to_renew        BOOLEAN     NOT NULL DEFAULT FALSE,
    in_use          BOOLEAN     NOT NULL DEFAULT FALSE,
    employee_id     BIGINT      REFERENCES employee(employee_id),
    created_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);