CREATE TABLE car (
    car_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_year INT NOT NULL DEFAULT 0,
    milage INT NOT NULL DEFAULT 0,
    to_replace BOOLEAN NOT NULL DEFAULT FALSE,
    last_serviced DATE,
    to_service BOOLEAN NOT NULL DEFAULT FALSE,
    need_to_service_date DATE,
    last_insurance_renewal DATE,
    insurance_expire_date DATE,
    to_renew_insurance BOOLEAN NOT NULL DEFAULT FALSE,
    in_use BOOLEAN NOT NULL DEFAULT true,
    employee_ID BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT car_employee_id_fkey 
        FOREIGN KEY (employee_id) 
        REFERENCES employee(employee_id) 
        ON DELETE CASCADE
)