CREATE TABLE car (
    car_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_year INT NOT NULL,
    milage INT NOT NULL,
    to_replace BOOLEAN NOT NULL DEFAULT FALSE,
    last_serviced DATE NOT NULL,
    to_service BOOLEAN NOT NULL DEFAULT FALSE,
    need_to_service_date DATE NOT NULL,
    last_insurance_renewal DATE NOT NULL,
    insurance_expire_date DATE NOT NULL,
    to_renew_insurance BOOLEAN NOT NULL DEFAULT FALSE,
    in_use BOOLEAN NOT NULL,
    employee_ID BIGINT REFERENCES employee(employee_id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)