CREATE TABLE id_card (
    id_card_id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id         BIGINT      REFERENCES employee(employee_id),
    last_renewed_date   DATE        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    need_to_renew_date  DATE        NOT NULL,  
    in_use              BOOLEAN     NOT NULL DEFAULT FALSE,
    to_renew            BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);