name: Deploy to DigitalOcean

# on each github push to master we attempt to deploy
# to server.
on:
  push:
    branches: [master]
    
# run tests after each push
# first setup code to be tested
# test to run on ubuntu instance on github's cloud. Copy code, fetch jdk with maven and have
# maven run the tests.
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'     
          distribution: 'temurin'
          cache: maven            

      - name: Run Unit & Integration Tests

        run: mvn clean test
        
# Deploy, we copy our code, have github runner ssh into our cloud server, inject 
# environmental variables stored in github secrets, and run the script at the bottom.
  deploy:
    needs: test 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Droplet via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          DB_USER: ${{ secrets.DB_USERNAME }}
          DB_PASS: ${{ secrets.DB_PASSWORD }}
          APP_DIR_USER: ${{ secrets.SSH_USER }} 
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          envs: DB_USER,DB_PASS,APP_DIR_USER
          script: |
            cd /home/$APP_DIR_USER/ERM-Employee-Item-Health-App
            
            # We have the server fetch the updated repo and force
            # it to delete the old version on disk.
            git fetch origin
            git reset --hard origin/master

            # Take docker container running down and force a rebuild using the new
            # container in the new repo. -f tells docker to use the docker-compose.yml file
            # -d is detached mode so it runs in background
            
            /usr/bin/docker compose -f docker-compose.yml down
            /usr/bin/docker compose -f docker-compose.yml up -d --build
            
            #Delete env variables so they are not left on server
            rm .env
